# Generated by Django 3.1.4 on 2021-11-04 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_user_followings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='followings',
            new_name='following_users',
        ),
    ]
