# Generated by Django 3.1.4 on 2020-12-16 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20201216_1621'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title', 'id']},
        ),
    ]
